### ISSUE TITLE
Error and sometimes a crash when i cap the second gate in mannhattan

### ISSUE THREAD

**Issue by JustBobTF** [caxanga334/tf-bewithrobots-redux#10]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/caxanga334/tf-bewithrobots-redux/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have checked that my issue still occours when using the plugin's default settings.
  - [ ] I am running the original plugin without third-party modifications.

# Environment
 * SourceMod version: 1.2.14
 * Plugin version: 1.11
 * [x] I have updated the plugin to the latest version available in the repository and my issue still happens.

# Description
Aaaand here we go again sorry if i'm disturbing... I got an error and sometimes a crash when i cap the second gate in Mannhattan.

Yes! I use an edited version of the plugin, i removed the Freezeinput, Weapon use restriction on spawn, command restrictions like kill, explode and dropitem (not all commands) and i removed the mini dispenser... 

I tested everything even with the fresh plugin install and also a fresh server install.

Again i'm sorry if i'm disturbing i love this plugin.

![Screenshot_5](https://user-images.githubusercontent.com/117551794/200976965-0e5cfc3f-d1b8-4a4f-b6d5-c160bda7049b.png)

# Steps to reproduce

Cap the second gate in mannhattan.

**Comment by caxanga334** [comment]
Which operating system is the server running?

**Comment by JustBobTF** [comment]
Windows

**Comment by caxanga334** [comment]
[Try this version.](https://github.com/caxanga334/tf-bewithrobots-redux/actions/runs/3433869324)

Remember to update your gamedata file.

**Comment by JustBobTF** [comment]
Good afternoon! it's working properly now thank you so much! 😃
