### ISSUE TITLE
Broken Due to TF2's 2022-12-01 Update

### ISSUE THREAD

**Issue by caxanga334** [caxanga334/tf-bewithrobots-redux#11]
~~Plugin is currently broken.~~
Fix implemented.

## Issues

- Gamedata is outdated. **Fixed**
- Errors due to alliedmodders/sourcemod#1871 **Fixed**

**Comment by caxanga334** [comment]
Update is out. Keeping this open until I have a confirmation that things are working fine for Windows.

**Comment by CombineSlayer24** [comment]
> Update is out. Keeping this open until I have a confirmation that things are working fine for Windows.

I'll check if this works on my Windows server.

**Comment by CombineSlayer24** [comment]
> > Update is out. Keeping this open until I have a confirmation that things are working fine for Windows.
> 
> I'll check if this works on my Windows server.

BWRR works on my Windows server. Seems to be all fine and dandy.
