### ISSUE TITLE
Errors on compile completion

### ISSUE THREAD

**Issue by Comicsanswich** [caxanga334/tf-bewithrobots-redux#16]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/caxanga334/tf-bewithrobots-redux/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have checked that my issue still occours when using the plugin's default settings.
  - [X] I am running the original plugin without third-party modifications.
  - [X] I have checked that I have all the required dependencies in order to compile and run the plugin.

# Environment
 * SourceMod version: 6927
 * Plugin version: 1.2.17a
 * [X] I have updated the plugin and sourcemod to the latest version available in the repository and my issue still happens.

# Description
I got errors on completion for tf_bwr_redux.sp
![image_2023-01-16_181809317](https://user-images.githubusercontent.com/28740793/212778988-5cbcd916-6bfb-45e7-9301-612bdaa9bf32.png)

# Steps to reproduce

**Comment by CombineSlayer24** [comment]
It looks like you're missing TFUtils. Do you have it installed?

**Comment by caxanga334** [comment]
CI build passed. The issue is on your end. Try downloading SM and the plugin dependencies again.

**Comment by Comicsanswich** [comment]
Yes I have TFUtils and made sure by redownloading it. I'll try your suggestion by redownloading all that again

**Comment by Comicsanswich** [comment]
The issue's been fixed thanks closing this now
