### ISSUE TITLE
Player Robots slide when deploying.

### ISSUE THREAD

**Issue by Comicsanswich** [caxanga334/tf-bewithrobots-redux#18]
# Help us help you
  - [X] I have checked that my issue [doesn't exist yet](https://github.com/caxanga334/tf-bewithrobots-redux/issues).
  - [X] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have checked that my issue still occours when using the plugin's default settings.
  - [X] I am running the original plugin without third-party modifications.

# Environment
 * SourceMod version: 6934
 * Plugin version: 1.2.17a
 * [X] I have updated the plugin to the latest version available in the repository and my issue still happens.

# Description
There's a bug where when deploying the bomb doesn't instantly stop the Player robots like with TFbot robots.

# Video
Here's the video of it
The file is too big for GitHub so I uploaded it to discord
https://cdn.discordapp.com/attachments/1087494790733639771/1087494995033993226/Team_Fortress_2_-_OpenGL_2023-03-20_17-50-51.mp4

# Steps to reproduce
Grab the bomb/flag (highly recommend using super scout for a better chance to reproduce this bug) go to the deploy area and deploy the bomb while running.

**Comment by caxanga334** [comment]
Not a plugin bug, that's how the player physics works. Still a nice enhancement to add.
Confirmed working on my test server. Please test and report.
[Download available here.](https://github.com/caxanga334/tf-bewithrobots-redux/actions/runs/4647671908)

**Comment by Comicsanswich** [comment]
> Not a plugin bug, that's how the player physics works. Still a nice enhancement to add. Confirmed working on my test server. Please test and report. [Download available here.](https://github.com/caxanga334/tf-bewithrobots-redux/actions/runs/4647671908)

I've tested it and still slides a bit but I can see a huge difference with the build you sent here a few hours ago I made another video so you can compare the video I sent earlier with the public build and the test build you sent me here: https://cdn.discordapp.com/attachments/1087494790733639771/1094458366568443904/Team_Fortress_2_-_OpenGL_2023-04-08_22-51-06.mp4

**Comment by caxanga334** [comment]
[Test this build.](https://github.com/caxanga334/tf-bewithrobots-redux/actions/runs/4648728851)

**Comment by Comicsanswich** [comment]
> [Test this build.](https://github.com/caxanga334/tf-bewithrobots-redux/actions/runs/4648728851)

Works like a charm here's the video right here: https://cdn.discordapp.com/attachments/1087494790733639771/1094499424404787290/Team_Fortress_2_-_OpenGL_2023-04-09_01-45-39.mp4
