### ISSUE TITLE
[Bug] Teleporter effect is not placed correctly

### ISSUE THREAD

**Issue by JustBobTF** [caxanga334/tf-bewithrobots-redux#32]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/caxanga334/tf-bewithrobots-redux/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have checked that my issue still occours when using the plugin's default settings.
  - [x] I am running the original plugin without third-party modifications.

# Environment
 * SourceMod version: 1.11
 * Plugin version: 1.2.19
 * [x] I have updated the plugin to the latest version available in the repository and my issue still happens.

# Description

The Robot Engineer teleporter effect is not on the correct position.
![20230923121135_1](https://github.com/caxanga334/tf-bewithrobots-redux/assets/117551794/913b8eed-2cf6-4220-b1b1-54c4a346e3f4)
![20230923121125_1](https://github.com/caxanga334/tf-bewithrobots-redux/assets/117551794/5d716bcc-3dc9-4012-a0c1-d7e4afefc832)
![20230923120910_1](https://github.com/caxanga334/tf-bewithrobots-redux/assets/117551794/9eb48f5f-e09f-41c0-89de-e59f2abb4333)

# Steps to reproduce

Place a teleporter exit and the effect will appear coming under the teleporter.

**Comment by JustBobTF** [comment]
Normally the effect comes like this
![20230923123659_1](https://github.com/caxanga334/tf-bewithrobots-redux/assets/117551794/00b9b9cb-9d56-4395-a23d-ea1267fa4fa3)

**Comment by TehPlayer14** [comment]
I've never seen this happen, looks like particle height is somehow 0 or less and deep in the floor
