### ISSUE TITLE
Player Blu spy robot player to be more accurate to the TFbot spy robots.

### ISSUE THREAD

**Issue by Comicsanswich** [caxanga334/tf-bewithrobots-redux#34]
**Is your feature request related to a problem? Please describe.**
Yes so I noticed that bwrr robot spy's cloak mechanic is not being accurate to what the **TFCord** TFbots use.
**Describe the solution you'd like**
For Robot Player Spies to not be able to attack while cloaked like with TFbots.
**Describe alternatives you've considered**
There is a **TFcord** that TFbots use and the now discontinued BWR2 aka BeWithRobots2 also uses this **TFcord** being `TFCond_Cloaked`
**Does this feature have dependencies?**
Does this features requites a plugin or extension to be installed?
Yes or No.
No
**Additional context**
Here's a screenshot of the **TFcord** that I replaced `TFCond_Stealthed` in `functions.sp`.
![image](https://github.com/caxanga334/tf-bewithrobots-redux/assets/28740793/bb0e9f22-63fa-43a7-bbfa-36625ac64b96)

Here's the video showcasing of the `TFCond_Cloaked` replacing `TFCond_Stealthed` the file is too big for GitHub so I uploaded it to discord.
https://cdn.discordapp.com/attachments/1087494790733639771/1180371690321100820/Team_Fortress_2_2023-12-01_23-18-45.mp4

**Comment by Comicsanswich** [comment]
> BWRR uses `TFCond_Stealthed` instead of `TFCond_Cloaked` so spies equipped with the dead ringer can actually use the DR feign death ability.
> 
> While `TFCond_Cloaked` doesn't prevent the spy from using the DR. Spies will have to wait for it to recharge and hope nobody hears the first decloak.
> 
> Also, bots doesn't use the `TFCond_Cloaked` condition. They press their virtual right mouse button, which will cloak them with the default invis watch.

I see is there a workaround to prevent Bwrr player spy robots from attacking while cloaked after teleporting?

**Comment by TehPlayer14** [comment]
One could swap watches on the fly, give default on spawn and then original after first decloak, or like spawn dead ringer that works as normal watch and then after first decloak attach the right attribute/give normal working dead ringer

Alternatively block attacking via an TFCond like bonked, or hook user command and always return -attack/ manipulate next attack delay via a property so its long

Another option is to give dead ringer initial attribute on spawn of quiet uncloak from the removed Saharan Spy set and then removing it after decloak
