### ISSUE TITLE
Make option to Disable func_respawnroom please

### ISSUE THREAD

**Issue by HeIIoween** [caxanga334/tf-bewithrobots-redux#4]
For some custom missions bots are not moving. So they are always under uber at their starting point.
Workaround is to disable "func_respawnroom" by Stripper: Source.

But i see that your plugin creates "func_respawnroom" back ...

Make option to Disable func_respawnroom please.

**Comment by caxanga334** [comment]
Please use the "Feature request" template when creating this type of issue.
