### ISSUE TITLE
Update gamedata

### ISSUE THREAD

**Issue by CopCorvette** [caxanga334/tf-bewithrobots-redux#7]
Server crashing while connecting after the last update

**Comment by caxanga334** [comment]
Unable to confirm on both Windows & Linux. I need more information such as crash dumps. I recommend installing [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703).

**Comment by CopCorvette** [comment]
Ah, sorry i'm new to this issue reporting thing, well it happened on windows and i forgot to mention that i updated my sourcemod and i checked the logs theres no errors pointing to the plugin the server simply closes himself when i'm in the Sending Client Info part but when i try without the plugin the server doesn't crash!

i really apologize if i didn't reported correctly
