### ISSUE TITLE
Getting error on plugin startup

### ISSUE THREAD

**Issue by JustBobTF** [caxanga334/tf-bewithrobots-redux#9]
# Help us help you
  - [x] I have checked that my issue [doesn't exist yet](https://github.com/caxanga334/tf-bewithrobots-redux/issues).
  - [x] I have tried my absolute best to reduce the problem-space and have provided the absolute smallest test-case possible.
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have checked that my issue still occours when using the plugin's default settings.
  - [x] I am running the original plugin without third-party modifications.

# Environment
 * SourceMod version: 1.11
 * Plugin version: 1.2.14
 * [x] I have updated the plugin to the latest version available in the repository and my issue still happens.

# Description

Hey i'm getting an error on startup after i updated to the last version in the repository.

![image](https://user-images.githubusercontent.com/117551794/200708084-bcd6969c-9767-4321-9050-8fd5d2eecb5e.png)

# Steps to reproduce

**Comment by caxanga334** [comment]
I was unable to reproduce the issue on a fresh install. The error log points to your gamedata file being outdated.

**Comment by JustBobTF** [comment]
Good evening! Now the plugin works thank you for the help! I'm closing this 😄
